name: Compile V2 Check

on: 
  push:
    paths:
      - V2GameRectangularPrism/**
      - .github/workflows/compile-v2-check.yml

jobs:
  main:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Compile
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - V2GameRectangularPrism
          fqbn: "arduino:samd:nano_33_iot"
          libraries: |
            - name: Adafruit GFX Library
            - name: Adafruit SSD1306
            - name: Arduino_LSM6DS3
            - name: Adafruit SHTC3 Library
