name: Compile V2 Check

on: 
  push:
#    paths:
#      - V2GameRectangularPrism/**

jobs:
  main:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Compile
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - V2GameRectangularPrism
          fqbn: "arduino:samd:nano_33_iot"
          libraries: |
            - name: Adafruit_GFX
            - name: Adafruit_SSD1306
            - name: Arduino_LSM6DS3
            - name: Adafruit_SHTC3
