name: Compile V1 Check

on: 
  push:
    paths:
      - V1GameRectangularPrism/**

jobs:
  main:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Compile
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - V1GameRectangularPrism
          fqbn: "arduino:megaavr:nona4809"
          libraries: |
            - name: Adafruit GFX Library
            - name: Adafruit SSD1306
