name: Format V1 Check

on: 
  push:
    paths:
      - V1GameRectangularPrism/**
      - .github/workflows/format-v1-check.yml

jobs:
  main:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Format
        uses: DoozyX/clang-format-lint-action@v0.18
        with:
          source: "V1GameRectangularPrism"
          extensions: "cpp,h,ino"
          clangFormatVersion: 14
