name: Format V2 Check

on: 
  push:
    paths:
      - V2GameRectangularPrism/**
      - .github/workflows/format-v2-check.yml

jobs:
  main:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Format
        uses: DoozyX/clang-format-lint-action@v0.18.2
        with:
          source: "V2GameRectangularPrism"
          extensions: "cpp,h,ino"
          clangFormatVersion: 14
